### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by sauravhiremath**
This adds the installation of oauth2client in the requirements.

### CODE REVIEW

**Comment by nithinmurali** [comment]
`oauth2client` dependency is removed in 2.x. Please change the target branch to `maint-1.1.4`.

**Comment by sauravhiremath** [comment]
I am unable to change the target branch. It cannot find an option to change it.
Any help with this, would be appreciated!

**Comment by nithinmurali** [comment]
Create a new PR. Then you can choose a branch to merge i think.

**Comment by sauravhiremath** [comment]
Oh, I was thinking we could change the target branch in a pre-existing issue itself. 
I'll create a new PR 👍

**Pull request closed without merging**
