### PR TITLE
Implemented updated property

### PR DESCRIPTION
**Pull request by e-beach**
Add the updated property -- how does this look?

### CODE REVIEW

**Comment by nithinmurali** [comment]
It looks Good. Can you please add a small test for it in the `online_test.py` ? Also remove the  `(use drive api)` from docs.

**Comment by e-beach** [comment]
I believe that I fixed the request. For the test, I just used the [gspread implementation](https://github.com/burnash/gspread/blob/6b1bb1ef6db8b318e3da5053ab173add853d3fe0/tests/test.py#L204-L208)

**Comment by nithinmurali** [comment]
Great! That will do

**Comment by nithinmurali** [comment]
fixes #34

**Pull request merged**
