### PR TITLE
Update cell documentation

### PR DESCRIPTION
**Pull request by Kordishal**
Updated most of the doc strings in the cell module. Fixed several typos and hopefully made it clearer overall.

### CODE REVIEW

**Comment by nithinmurali** [comment]
Thanks for taking the effort to fix the docs. Please fix the conflict :)

**Comment by Kordishal** [comment]
In set text alignment you check for 'horizondal' instead of horizontal. Should I re-factor this? Currently the docs do reflect the typo. I could add a check for horizondal which changes it to horizontal to not make it a breaking change.

**Comment by nithinmurali** [comment]
Yes, please refactor it to a non breaking change. Just add  `or` check for horizontal and change all docs to horizontal.

**Comment by nithinmurali** [comment]
Thanks for the PR

**Pull request merged**
