### PR TITLE
fix for issue #128

### PR DESCRIPTION
**Pull request by axil**

### CODE REVIEW

**Comment by axil** [comment]
Not sure how to change this PR, I've created another one, https://github.com/nithinmurali/pygsheets/pull/131

My goal was to get a conversion from a cell name to the cell json:

```
pygsheets.DataRange(start=start, end=end, worksheet=sheet)._get_gridrange()
```
in order to change cell formatting in batch:

```python
def update_format(start, end, text_format):
    sheet.client.sh_batch_update(book.id, {
        'repeatCell':{
            'range': pygsheets.DataRange(start=start, end=end, 
                                         worksheet=sheet)
                              ._get_gridrange(),
            'cell': {'userEnteredFormat': {
                'textFormat': text_format
            }},
            'fields': 'userEnteredFormat.textFormat',
        }
    })
```

And the DataRange was complaining in a strange way. With this PR it works perfectly well :)

**Comment by nithinmurali** [comment]
Wow. Actually you have an easier (if not official) way of achieving this. Create a Datarange of start to end and call `apply_format`. You can think of creating a Datarange selecting a set of cells in web UI.

**Comment by axil** [comment]
I understand that this patch will not fix the problem if `data` is not `None`
    if len(data) != end[0] - start[0] + 1 or len(data[0]) != end[1] - start[1] + 1:
        self._data = data
but considering that noone raised a ticket about it, it is not so critical. 

On the other hand the line I'm suggesting to remove is definitely a bug as it generates an error in a obviously correct use case.

**Comment by axil** [comment]
> Create a Datarange of start to end and call apply_format. You can think of creating a Datarange as selecting a set of cells in web UI.

I gave it a try, but instead of changing the color only it deleted everything in the range.

Is there a way to change the color without deleting the content?

PS Also there's a spelling error: it should be `apply_format`, no `applay_format`.

**Pull request closed without merging**
